# Netlify deployment configuration
# Alternative static hosting option

[build]
  base = "frontend"
  publish = "build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"